name: DeepRL-Pose-Control
channels:
  - defaults
dependencies:
  - python=3.8.15
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - ca-certificates=2022.10.11
  - certifi=2022.9.24
  - ld_impl_linux-64=2.38
  - libffi=3.4.2
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - ncurses=6.3
  - openssl=1.1.1s
  - pip=22.3.1
  - readline=8.2
  - setuptools=65.5.0
  - sqlite=3.40.0
  - tk=8.6.12
  - wheel=0.37.1
  - xz=5.2.8
  - zlib=1.2.13
  - pip:
    - absl-py==1.3.0
    - cachetools==5.2.0
    - catkin-pkg==0.5.2
    - catkin-tools==0.9.0
    - cffi==1.15.1
    - charset-normalizer==2.1.1
    - cloudpickle==2.2.0
    - contourpy==1.0.6
    - cryptography==40.0.1
    - cycler==0.11.0
    - decorator==5.1.1
    - distro==1.8.0
    - docutils==0.19
    - fonttools==4.38.0
    - freetype-py==2.3.0
    - gitdb==4.0.10
    - gitpython==3.1.32
    - google-auth==2.15.0
    - google-auth-oauthlib==0.4.6
    - grpcio==1.51.1
    - gspread==5.8.0
    - gym==0.21.0
    - gym-notices==0.0.8
    - gymnasium==0.27.0
    - gymnasium-notices==0.0.1
    - httplib2==0.22.0
    - idna==3.4
    - imageio==2.25.0
    - importlib-metadata==4.13.0
    - jax-jumpy==0.2.0
    - kiwisolver==1.4.4
    - lxml==4.9.2
    - markdown==3.4.1
    - markupsafe==2.1.1
    - matplotlib==3.6.2
    - networkx==2.2
    - numpy==1.23.5
    - nvidia-cublas-cu11==11.10.3.66
    - nvidia-cuda-nvrtc-cu11==11.7.99
    - nvidia-cuda-runtime-cu11==11.7.99
    - nvidia-cudnn-cu11==8.5.0.96
    - oauth2client==4.1.3
    - oauthlib==3.2.2
    - osrf-pycommon==2.0.2
    - packaging==22.0
    - pandas==1.5.2
    - pillow==9.3.0
    - ply==3.11
    - protobuf==3.20.3
    - pyaml==21.10.1
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pybullet==3.2.5
    - pycollada==0.6
    - pycparser==2.21
    - pyglet==1.5.27
    - pyopengl==3.1.0
    - pyopenssl==23.1.1
    - pyparsing==3.0.9
    - pyquaternion==0.9.9
    - pyrender==0.1.45
    - python-dateutil==2.8.2
    - pytz==2022.6
    - pyyaml==6.0
    - requests==2.28.1
    - requests-oauthlib==1.3.1
    - robot-descriptions==1.6.0
    - rospkg==1.4.0
    - rsa==4.9
    - ruamel-yaml-clib==0.2.7
    - sb3-contrib==1.7.0
    - scipy==1.9.3
    - seaborn==0.12.2
    - shimmy==0.1.0
    - sip==6.7.6
    - six==1.16.0
    - smmap==5.0.0
    - snakeviz==2.1.1
    - stable-baselines3==1.7.0
    - tensorboard==2.11.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-customizable-plots==1.1.3
    - tensorboard-plugin-wit==1.8.1
    - toml==0.10.2
    - torch==1.13.0
    - tornado==6.2
    - tqdm==4.65.0
    - trimesh==3.18.1
    - typing-extensions==4.4.0
    - urdf-parser-py==0.0.4
    - urdfpy==0.0.22
    - urllib3==1.26.13
    - werkzeug==2.2.2
    - zipp==3.11.0
