#################### PATHS ####################
modelSavePath: '/home/tumu/anaconda3/envs/stableBaselines/panda-gym/modelhpc'
logSavePath: '/home/tumu/anaconda3/envs/stableBaselines/panda-gym/loghpc'
urdfPath: '/home/tumu/anaconda3/envs/stableBaselines/panda-gym/panda_gym/envs/robots/panda.urdf'
#urdfPath: '/home/tumu/anaconda3/envs/stableBaselines/panda-gym/panda_gym/envs/robots/jaco_robotiq_object.urdf'
#modelSavePath: '/scratch/users/tbal21/.conda/envs/stableBaselines/panda-gym/modelhpc'
#logSavePath: '/scratch/users/tbal21/.conda/envs/stableBaselines/panda-gym/loghpc'
#urdfPath: '/kuacc/users/tbal21/panda_gym/envs/robots/panda.urdf'
expNumber: 354
envName: "PandaReach-v2"            
total_timesteps: !!float 32768000
mode: False                       
algorithm: "PPO"                 
policy: "MultiInputPolicy"           
render: True                        
gamma: 0.95 
n_steps: 4096
n_epochs: 10
batch_size: 2048
learning_rate: 0.0003
n_envs: 16
testSamples: 1000
testSampleOnTraining: 500
evalFreqOnTraining: 2000000
max_episode_steps: 800
verbose: 1
pseudoI: False
networkOutput: True
save_freq: !!float 100e6
sampleJointAnglesGoal: True     # If this is false, then you should determine goal_range value
goal_range: 0.3
randomStart: True              # If this is false,, then you should determine neutral joint angles.. These values are defined in myrobot.py
lambdaErr: 100.0
accelerationConstant: 0.0
velocityConstant: 0.1
velocityNormThreshold: 0.05
thresholdConstant: 0.0
alpha: 1.0
activation_fn: 0 # ReLU:1, Tanh: 0
hiddenUnits: 128
CurriLearning: True # If this is false, then you should determine the low limit and high limit angle in myrobot.py
jointLimitLowStartID: 'W0Low'
jointLimitHighStartID: 'W0High'
rmseThreshold: 0.012
maeThreshold: 0.012
avgJntVelThreshold: 0.1
orientationConstant: 1
net_arch: [{'pi': [128, 128],
            'vf': [128, 128]}]